// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFplby2PuQPUCqtBhESukj3v3DnW-PvaY',
    appId: '1:71909924557:web:2319d2dcfe14ed059f1384',
    messagingSenderId: '71909924557',
    projectId: 'flutterbootcamb',
    authDomain: 'flutterbootcamb.firebaseapp.com',
    storageBucket: 'flutterbootcamb.appspot.com',
    measurementId: 'G-SLZGS66ZJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO_9VbztZcqbWbc-UWv-ahH2Zl0NOVx-k',
    appId: '1:71909924557:android:e22f45844c8df1f59f1384',
    messagingSenderId: '71909924557',
    projectId: 'flutterbootcamb',
    storageBucket: 'flutterbootcamb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGpaDVm6hams0Pm2zo2W90PrnLsa0XkZo',
    appId: '1:71909924557:ios:1b04381ce9ed5ab79f1384',
    messagingSenderId: '71909924557',
    projectId: 'flutterbootcamb',
    storageBucket: 'flutterbootcamb.appspot.com',
    iosBundleId: 'com.example.googleFlutterBootcamb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGpaDVm6hams0Pm2zo2W90PrnLsa0XkZo',
    appId: '1:71909924557:ios:358af36ce3740ddc9f1384',
    messagingSenderId: '71909924557',
    projectId: 'flutterbootcamb',
    storageBucket: 'flutterbootcamb.appspot.com',
    iosBundleId: 'com.example.googleFlutterBootcamb.RunnerTests',
  );
}
